hub:
  config:
    JupyterHub:
      authenticator_class: dummy
    KubeSpawner:
      k8s_api_request_timeout: 12345
  db:
    url: sqlite:////data/jupyterhub.sqlite
  service:
    type: ClusterIP
  extraVolumes:
    - name: jupyterhub-db
      persistentVolumeClaim:
        claimName: jupyterhub-pvc
  extraVolumeMounts:
    - name: jupyterhub-db
      mountPath: /data
  config:
    Authenticator:
      admin_users:
        - admin

proxy:
  secretToken: "c413fe27d65c5916b7cf4028bf49a19b3056d59f2c2d1e79349244a6f758babe"
  https:
    enabled: false
  service:
    type: ClusterIP

singleuser:
  image:
    name: "jupyter/minimal-notebook"
    tag: "latest"
  storage:
    type: none

cull:
  enabled: true
  timeout: 600
  every: 60
