---
- name: Install kubernetes library for Python
  ansible.builtin.pip:
    name: kubernetes

- name: Clone ray project
  changed_when: false
  ansible.builtin.git:
    repo: https://github.com/danielcristho/ray-jupyterlab-k3s.git
    dest: /home/ubuntu/ray-jupyterlab-k3s
    clone: true

- name: Install network plugin
  kubernetes.core.k8s:
    kubeconfig: /home/ubuntu/.kube/config
    src: /home/ubuntu/ray-jupyterlab-k3s/infra/raycluster/manifests/calico.yaml
    state: present